AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for auto stop(delete) and start(create) multiple NAT Gateways
#
# Metadata
#
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: CloudWatch Events Configuration
      Parameters:
      - StartSchedule
      - StopSchedule
    - Label:
        default: VPC Configuration
      Parameters:
      - NatGatewayConfigs

#
# Parameters
#
Parameters:
  StartSchedule:
    Description: Start Datetime(UTC) format cron
    Default: 0 21 ? * SUN-THU *
    Type: String
  StopSchedule:
    Description: Stop Datetime(UTC) format cron
    Default: 0 15 ? * MON-FRI *
    Type: String
  # NAT Gatewayの設定
  NatGatewayConfigs:
    Description: List of NAT Gateway configurations in JSON format
    Type: String
    Default: '[
      {
        "EipAllocId":"eipalloc-xxxxxxxxxx",
        "SubnetId":"subnet-xxxxxxxxxx",
        "RouteTableIds":["rtb-xxxxxxxxxx","rtb-xxxxxxxxxx"]
      },
      {
        "EipAllocId":"eipalloc-xxxxxxxxxx",
        "SubnetId":"subnet-xxxxxxxxxx",
        "RouteTableIds":["rtb-xxxxxxxxxx"]
      }
    ]'

#
# Resources
#
Resources:
  StateSchedulerExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaExecPolicy
        PolicyDocument:
          Statement:
          - Sid: AccessToCWLog
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
          - Sid: ChangeNatgwAndRouteTable
            Effect: Allow
            Action:
            - ec2:CreateNatGateway
            - ec2:DeleteNatGateway
            - ec2:DescribeNatGateways
            - ec2:CreateRoute
            - ec2:DeleteRoute
            - ec2:DescribeRouteTables
            Resource: "*"
  StartScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule for start
      ScheduleExpression: !Sub cron(${StartSchedule})
      State: ENABLED
      Targets:
      - Arn: !GetAtt [ StateSchedulerFunction, Arn ]
        Id: StateSchedulerFunction
  StopScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: ScheduledRule for stop
      ScheduleExpression: !Sub cron(${StopSchedule})
      State: ENABLED
      Targets:
      - Arn: !GetAtt [ StateSchedulerFunction, Arn ]
        Id: StateSchedulerFunction
  PermissionForStartEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StateSchedulerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [ StartScheduledRule, Arn ]
  PermissionForStopEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StateSchedulerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt [ StopScheduledRule, Arn ]
  StateSchedulerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          NatGatewayConfigs: !Ref NatGatewayConfigs
      Description: Scheduled NAT Gateway stop and start.
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt [ StateSchedulerExecRole, Arn ]
      Runtime: python3.12
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import os
          import logging
          import urllib.request
          import json
          import datetime
          
          logger = logging.getLogger(__name__)
          logger.setLevel(logging.INFO)
          
          # 環境変数から情報取得
          NAT_GATEWAY_CONFIGS = json.loads(os.environ['NatGatewayConfigs'])
          
          ec2 = boto3.client('ec2')
          
          # 祝日チェック
          def holiday_check():
              today = (datetime.datetime.now() + datetime.timedelta(hours=9)).strftime('%Y-%m-%d')
              holiday_url = 'https://holidays-jp.github.io/api/v1/date.json'
              req = urllib.request.Request(holiday_url)          
              with urllib.request.urlopen(req) as res:
                  holiday_list = json.load(res)
              try:
                  logger.info('本日%sは%sで祝日です。スキップします。',today,holiday_list[today])
                  return True
              except KeyError as e:
                  logger.info('本日%sは祝日ではありません。続行します。',today)
                  return False
          def schedule_natgateway(event):
              for config in NAT_GATEWAY_CONFIGS:
                  eip_alloc_id = config['EipAllocId']
                  subnet_id = config['SubnetId']
                  route_table_ids = config['RouteTableIds']
                  
                  if any(r for r in event.get('resources') if 'StartScheduledRule' in r):
                      logger.info('Create NAT Gateway')
                      response = ec2.create_nat_gateway(AllocationId=eip_alloc_id, SubnetId=subnet_id)
                      logger.info(response)
                      natgw_id = response['NatGateway']['NatGatewayId']
                      logger.info('Waiting for creating NAT Gateway')
                      ec2.get_waiter('nat_gateway_available').wait(NatGatewayIds=[natgw_id])
                      logger.info('NAT Gateway is available')
                      
                      for route_table_id in route_table_ids:
                          logger.info('Change Route Table')
                          logger.info(ec2.create_route(DestinationCidrBlock='0.0.0.0/0', NatGatewayId=natgw_id, RouteTableId=route_table_id))
                  
                  elif any(r for r in event.get('resources') if 'StopScheduledRule' in r):
                      logger.info('Delete NAT Gateway')
                      filters = [{'Name': 'subnet-id', 'Values': [subnet_id]}, {'Name': 'state', 'Values': ['available']}]
                      response = ec2.describe_nat_gateways(Filters=filters)
                      natgw = response['NatGateways'][0]['NatGatewayId']
                      logger.info(ec2.delete_nat_gateway(NatGatewayId=natgw))
                      
                      for route_table_id in route_table_ids:
                          logger.info('Change Route Table')
                          logger.info(ec2.delete_route(DestinationCidrBlock = '0.0.0.0/0', RouteTableId = route_table_id))
          def lambda_handler(event, context):
              logger.info('Started')
              if not holiday_check():
                  schedule_natgateway(event)
              logger.info('Complete')